name: HostelNavigator Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup React Env
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Checkout 
        uses: actions/checkout@v4.1.4

      - name: Deploy Site
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
